accounts/urls.py
from django.urls import path
from .views import *


app_name = "accounts"

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

stockapp/urls.py
from django.contrib import admin
from django.urls import path,include
from stockmgt import views as stock_view 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', stock_view.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('stock/', include('stockmgt.urls')),
]

stockmgt/urls.py
from django.urls import path
from .views import *

app_name = 'stock'

urlpatterns = [
    path('list/', list_items, name='list'),
    path('add/', add_items, name='add'),
    path('add_category/', add_category, name='add_category'),
    path('update/<str:id>/', update_item, name='update'),
    path('delete/<str:id>/', delete_item, name='delete'),
    path('detail/<str:id>/', stock_detail, name="detail"),
    path('issue/<str:id>/', issue_item, name="issue"),
    path('receive/<str:id>/', receive_item, name="receive"),
    path('reorder/<str:id>/', reorder_level, name="reorder"),
    path('history/', history, name='history'),
]

stockmgt/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class Category(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name

class Stock(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    item_name = models.CharField(max_length=50, blank=True, null=True)
    quantity = models.IntegerField(default='0', blank=True, null=True)
    receive_quantity = models.IntegerField(default='0', blank=True, null=True)
    receive_by = models.CharField(max_length=50, blank=True, null=True)
    issue_quantity = models.IntegerField(default='0', blank=True, null=True)
    issue_by = models.CharField(max_length=50, blank=True, null=True)
    issue_to = models.CharField(max_length=50, blank=True, null=True)
    phone_number = models.CharField(max_length=50, blank=True, null=True)
    created_by = models.CharField(max_length=50, blank=True, null=True)
    reorder_level = models.IntegerField(default='0', blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    export_to_CSV = models.BooleanField(default=False)

    def __str__(self):
        return self.item_name

class StockHistory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    item_name = models.CharField(max_length=50, blank=True, null=True)
    quantity = models.IntegerField(default='0', blank=True, null=True)
    receive_quantity = models.IntegerField(default='0', blank=True, null=True)
    receive_by = models.CharField(max_length=50, blank=True, null=True)
    issue_quantity = models.IntegerField(default='0', blank=True, null=True)
    issue_by = models.CharField(max_length=50, blank=True, null=True)
    issue_to = models.CharField(max_length=50, blank=True, null=True)
    phone_number = models.CharField(max_length=50, blank=True, null=True)
    created_by = models.CharField(max_length=50, blank=True, null=True)
    reorder_level = models.IntegerField(default='0', blank=True, null=True)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=False, null=True)
    timestamp = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

@receiver(post_save, sender=Stock)
def copy_stock_to_history(sender, instance, created, **kwargs):
    """
    Signal handler to copy Stock data to StockHistory when creating/updating Stock.
    """
    if created or kwargs.get('update_fields'):
        StockHistory.objects.create(
            category=instance.category,
            item_name=instance.item_name,
            quantity=instance.quantity,
            receive_quantity=instance.receive_quantity,
            receive_by=instance.receive_by,
            issue_quantity=instance.issue_quantity,
            issue_by=instance.issue_by,
            issue_to=instance.issue_to,
            phone_number=instance.phone_number,
            created_by=instance.created_by,
            reorder_level=instance.reorder_level,
            last_updated=instance.last_updated,
            timestamp=instance.timestamp
        )

stockmgt/forms.py
from django import forms
from .models import *

class StockCreateForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['category', 'item_name', 'quantity', 'reorder_level']
        
    def clean_item_name(self):
          item_name = self.cleaned_data.get('item_name')
          if not item_name:
            raise forms.ValidationError("This field is required")
          for instance in Stock.objects.all():
              if instance.item_name == item_name:
                raise forms.ValidationError(str(item_name) + ' is already created')
          return item_name
        
    def clean_category(self):
          category = self.cleaned_data.get('category')
          if not category:
            raise forms.ValidationError("This field is required")
          return category
    
class StockUpdateForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['category', 'item_name', 'quantity']
        
    def clean_item_name(self):
          item_name = self.cleaned_data.get('item_name')
          if not item_name:
            raise forms.ValidationError("This field is required")
          return item_name
        
    def clean_category(self):
          category = self.cleaned_data.get('category')
          if not category:
            raise forms.ValidationError("This field is required")
          return category

class StockSearchForm(forms.ModelForm):
   class Meta:
     model = Stock
     fields = ['category', 'item_name', 'export_to_CSV']

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

class IssueForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['issue_quantity', 'issue_to']
        
class ReceiveForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['receive_quantity', 'receive_by']

class ReorderLevelForm(forms.ModelForm):
	class Meta:
		model = Stock
		fields = ['reorder_level']

stockmgt/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse
import csv

# Create your views here.
def home(request):
    context={
        'title':"Welcome to Stock Management System"
    }
    return render(request, 'stock/home.html', context)

@login_required(login_url=('/accounts/login'))
def list_items(request):
    title = "List of items"
    queryset = Stock.objects.all()
    form = StockSearchForm()
    context={
        'title':title,
        'queryset':queryset,
        'form':form
    }
    if request.method == 'POST':
        form = StockSearchForm(request.POST)
        if form.is_valid():
            queryset = Stock.objects.filter(
                    category__name__icontains=form['category'].value(),
                    item_name__icontains=form['item_name'].value()
                )
            
            context={
                'title':title,
                'queryset':queryset,
                'form':form
            }

            if form['export_to_CSV'].value() == True:
                response = HttpResponse(content_type='text/csv')
                response['Content-Disposition'] = 'attachment; filename="Stocklist.csv"'
                writer = csv.writer(response)
                writer.writerow(['CATEGORY', 'ITEM NAME', 'QUANTITY'])
                instance = queryset
                for stock in instance:
                    writer.writerow([stock.category, stock.item_name, stock.quantity])
                return response
       
    return render(request, 'stock/list.html', context)

@login_required(login_url=('/accounts/login'))
def add_items(request):
    title = "Add Items"
    if request.method == 'POST':
        form = StockCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('stock:list')
    else:
        form = StockCreateForm()
    
    return render(request, 'stock/add.html', {'form': form, "title":title})

@login_required(login_url=('/accounts/login'))
def update_item(request, id):
    title = "Edit Item"
    queryset = Stock.objects.get(id=id)
    form = StockCreateForm(instance=queryset)

    if request.method == 'POST':
        form = StockUpdateForm(request.POST,instance=queryset)
        if form.is_valid:
            form.save()
            messages.success(request, "Updated Successfully")
            return redirect('stock:list')

    context = {
        'title':title,
        'form':form
    }  
    return render(request, 'stock/add.html', context)

@login_required(login_url=('/accounts/login'))
def delete_item(request, id):
    queryset = Stock.objects.get(id=id)
    if request.method=='POST':
        queryset.delete()
        messages.success(request, "Deleted Successfully")
        return redirect('stock:list')
    return render(request, 'stock/delete.html')

@login_required(login_url=('/accounts/login'))
def add_category(request):
    title = "Add Category"
    form = CategoryForm()
    context={
        'title': title,
        'form':form
    }
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Category added Successfully")
            return redirect('stock:add')
    return render(request, 'stock/category.html', context)

@login_required(login_url=('/accounts/login'))
def stock_detail(request, id):
    title = "Stock Details"
    queryset = Stock.objects.get(id=id)
    context={
        'title':title,
        'queryset': queryset,
    }
    return render(request, 'stock/detail.html', context)

@login_required(login_url=('/accounts/login'))
def issue_item(request, id):
    title = "Issue Item"
    instance = Stock.objects.get(id=id)
    form = IssueForm()
    context = {
        'title':title,
        'queryset': instance,
        'form': form
    }
    
    if request.method == 'POST':
        form = IssueForm(request.POST)
        if form.is_valid():
            try:
                issue_quantity = int(form.cleaned_data['issue_quantity'])
                instance.quantity -= issue_quantity
                instance.save()
                return redirect('/stock/detail/' + str(instance.id))
            except ValueError:
                pass
    return render(request, "stock/add.html", context)




@login_required(login_url=('/accounts/login'))
def receive_item(request, id):
    title = "Receive Item"
    instance = Stock.objects.get(id=id)
    form = ReceiveForm()
    context = {
        'title':title,
        'queryset': instance,
        'form': form
    }
    
    if request.method == 'POST':
        form = ReceiveForm(request.POST)
        if form.is_valid():
            try:
                receive_quantity = int(form.cleaned_data['receive_quantity'])
                instance.quantity += receive_quantity
                instance.save()
                return redirect('/stock/detail/' + str(instance.id))
            except ValueError:
                pass
    return render(request, "stock/add.html", context)

@login_required(login_url=('/accounts/login'))
def reorder_level(request, id):
    title = "Reoder Level"
    queryset = Stock.objects.get(id=id)
    form = ReorderLevelForm(request.POST or None, instance=queryset)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Reorder level for " + str(instance.item_name) + " is updated to " + str(instance.reorder_level))
        return redirect("stock:list")
    context = {
            'title':title,
			"instance": queryset,
			"form": form,
		}
    return render(request, "stock/add.html", context)

@login_required(login_url=('/accounts/login'))
def history(request):
    title = 'Stock History'
    queryset = StockHistory.objects.all()
    context = {
        "title": title,
		"queryset": queryset,
	}
    return render(request, "stock/history.html",context)

stockmgt/templates/stock/add.html
{% extends 'stock/base.html' %}
{% load bootstrap5 %}
{% block content %}

    <div class="container mt-5">
        <h1 class="form title mb-5">{{ title }}</h1>
    </div>

    <form class="container mt-5" method="post" action="">
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
            <div class="col-sm-7">
                {% bootstrap_field field %}
            </div>
            {% endfor %}
        </div> 
        <input class="btn btn-success me-5" type="submit" value="Save"> 
    </form>

{% endblock%}

stockmgt/templates/stock/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SMS</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'home' %}"><img height="70px" src="{% static 'img/logo.png' %}" alt="logo"></a>

        <div class="collapse navbar-collapse" id="navbarNav">        
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'stock:list' %}">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'stock:add' %}">Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'stock:add_category' %}">Add Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'stock:history' %}">History</a>
                </li>
            </ul>
        </div>

        <ul class="navbar-nav">
            <li class="nav-item">
                    <a href="{% url 'accounts:logout' %}" class="btn btn-danger p-2">{{user}} | Logout</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="btn btn-success p-2" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item right">
                <a class="btn btn-info p-2" href="{% url 'accounts:signup' %}">Signup</a>
            </li>
        </ul>
        {% endif %}
    </nav>
    

    {% block content %}
    {% endblock %}
</body>
</html>

stockmgt/templates/stock/category.html
{% extends 'stock/base.html' %}
{% load bootstrap5 %}
{% block content %}

    <div class="container mt-5">
        <h1 class="form title mb-5">{{ title }}</h1>
    </div>

    <form class="container mt-5" method="post" action="">
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
            <div class="col-sm-7">
                {% bootstrap_field field %}
            </div>
            {% endfor %}
        </div> 
        <input class="btn btn-success" type="submit" value="Add"> 
    </form>

{% endblock%}

stockmgt/templates/stock/delete.html
{% extends 'stock/base.html' %}

{% block content %}
  <form class="container mt-5" method="post" action="">
      {% csrf_token %}
        <h1 class="form title">Are you sure you want to Delete?</h1>
        <div class="row mt-3">
          <div class="col-sm-3">
            <input class="btn btn-danger" type="submit" value="Delete" />
          </div>
          <div class="col-sm-3">
            <a href="{% url 'stock:list'%}"><div class="btn btn-primary">Cancel</div></a>
          </div>
          <div class="col-sm-3"></div>
          <div class="col-sm-3"></div>
      </div>
  </form>
{% endblock%}

stockmgt/templates/stock/detail.html
{% extends 'stock/base.html' %}
{% load bootstrap5 %}
{% block content %}

      <div class="container mt-5">
        <h1 class="title mb-5">{{ title }}</h1>
      </div>        
      <div class="container">
        <table>
                <tr>
                  <th>Item</th>
                  <th>Quantity</th>
                  <th>Last Updated</th>
                  <th>Reoder Level</th>
                </tr>
                <tr>
                  <td>{{queryset.item_name}}</td>
                  <td>{{queryset.quantity}}</td>
                  <td>{{queryset.last_updated}}</td>
                  <td>{{queryset.reorder_level}}</td>
                </tr>
        </table>
        <div class="row mt-5">
          <div class="col-sm-3"></div>
          <div class="col-sm-3"><a href='{% url "stock:issue" id=queryset.id%}'><div class='btn btn-primary'>ISSUE ITEM</div></a></div>
          <div class="col-sm-3"><a href='{% url "stock:receive" id=queryset.id%}'><div class='btn btn-success'>RECEIVE ITEM</div></a></div>
          <div class="col-sm-3"></div>
        </div>
      </div>
{% endblock %}

stockmgt/templates/stock/history.html
{% extends 'stock/base.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="title mb-5">{{ title }}</h1>
        <table>
            <thead>
                <th>#</th>
				<th>Item</th>
				<th>Category</th>
				<th>Quantity</th>
				<th>Reoder Level</th>
                <th>Issue Quantity</th>
                <th>Receive Quantity</th>
				<th>Timestamp</th>
				<th>Last Updated</th>
            </thead>
            <tbody>
                {% for instance in queryset %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ instance.item_name }}</td>
                    <td>{{ instance.category }}</td>
                    <td>{{ instance.quantity }}</td>
                    <td>{{ instance.reorder_level }}</td>
                    <td>{{ instance.issue_quantity }}</td>
                    <td>{{ instance.receive_quantity }}</td>
                    <td>{{ instance.timestamp }}</td>
                    <td>{{ instance.last_updated }}</td>
                </tr>
                {% endfor %}
            </tbody>
    
        </table>
    </div>

{% endblock %}

stockmgt/templates/stock/home.html
{% extends 'stock/base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="home mb-5">{{ title }}</h1>
            <img height="700px" src="{% static 'img/stock.jpg' %}" alt="stock">
        </div>
    </div>
</div>

{% endblock %}

stockmgt/templates/stock/list.html
{% extends 'stock/base.html' %}
{% load bootstrap5 %}
{% block content %}

	{% if messages %}
		{% for message in messages %}
		 	<div class="text-center mt-3">{{ message }}</div>
		{% endfor %}
	{% endif %}

	
	<div class="container mt-5">
		<h1 class="title mb-5">{{ title }}</h1>
		<form class="mt-5" method="post" action="">
			{% csrf_token %}
			<div class="row">
				{% for field in form %}
				<div class="col-sm-5">
					{% bootstrap_field field %}
				</div>
				{% endfor %}
				<div class="col-sm-3">
					<input class="btn btn-success" type="submit" value="Search">
				</div>
			</div> 
		</form>

		<table class="m-5">
			<thead>
				<th>#</th>
				<th>Item</th>
				<th>Category</th>
				<th>Quantity</th>
				<th>Reoder Level</th>
				<th>Timestamp</th>
				<th>Last Updated</th>
				<th>Delete</th>
			</thead>
			<tbody>
				{% for instance in queryset %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td><a href="{% url 'stock:update' id=instance.id %}">{{instance.item_name}}</a></td>
					<td>{{instance.category}}</td>
					<td><a href="{% url 'stock:detail' id=instance.id %}">
						{% if instance.quantity <= instance.reorder_level %}
						<div style="background-color: tomato;">{{instance.quantity}}</div>
						{% else %}{{instance.quantity}}
						{% endif %}
					</a></td>
					<td><a href="{% url 'stock:reorder' instance.id %}">{{instance.reorder_level}}</a></td>
					<td>{{instance.timestamp}}</td>
					<td>{{instance.last_updated}}</td>
					<td><a href="{% url 'stock:delete' id=instance.id %}"><i class="fas fa-trash" style="color: red;"></i></a></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	

{% endblock %}